### ISSUE TITLE
Can`t get GUID of Questionaire Item

### ISSUE THREAD

**Issue by Bacis55** [SlyNet/SurveySolutionsClient#9]
Hello, 
Can you help me please how can I get GUID of question item by API?
When I want to create new Assignment for a question inside roster I need to know Identity of question what is GUID + RosterVector(x).
So I get questionaire Items objects but there are only Variable.... Is GUID missing or am I looking for it in the wrong place?
Maybe using of (Variable + RosterVector) could be more simplier to use, if is it possible.

Thank you.
MB

![image](https://user-images.githubusercontent.com/65445700/135635252-46547764-b0d9-4f5d-895b-5eeca4c77a05.png)

**Comment by SlyNet** [comment]
Please submit full code of your method to see what properties do you include in graphql request

**Comment by Bacis55** [comment]
here is a code:

```
public async Task list_questionaireItems(DataGrid dg, DataTable dt)
        {
            var client = new SurveySolutionsApi(new HttpClient(), ClientSettings.GetConfiguration(cbox_ws.SelectedItem.ToString()));
            var builder = new HeadquartersQueryQueryBuilder()
                .WithQuestionnaireItems(
                new QuestionnaireItemQueryBuilder()
                .WithAllFields(),
                cbox_ws.SelectedItem.ToString(),
                        f_quest.QuestionnaireId,
                        f_quest.Version
                        );
            var result = await client.GraphQl.ExecuteAsync<GraphQlResponse>(builder);

            foreach (var dot in result.Data.QuestionnaireItems)
            {
                { _ = dt.Rows.Add(new object[] { dot.EntityType, dot.Title, dot.Label, dot.Type, dot.Options.Count }); }
            }
            dg.ItemsSource = dt.DefaultView;        
        }
````

I think there are missing Question GUID in result.Data.QuestionnaireItems (dot).

**Comment by SlyNet** [comment]
Graphql API does not provide question id in it. 
![image](https://user-images.githubusercontent.com/209227/141671237-761d7aed-9afe-46ca-8aa5-12a7516c79d1.png)

If you need question id you can get it from `/api/v1/questionnaires/{id}/{version}/document` endpoint, but as I'm aware all the endpoints that need it should accept either question id or question variable. Variables are more human readable so if it suits your needs you should be able to switch to it. 

`/api/v1/questionnaires/{id}/{version}/document`  is not covered by this client since response is heavily dependent on questionnaire you are accessing and if you need it use raw `HttpClient` to access it.
